name: main
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup msbuild
        uses: microsoft/setup-msbuild@v2

      - name: build external dependencies
        shell: cmd
        working-directory: framework/external
        run: call build_externals_windows.bat

      - name: Configurar Gráficos Virtuales (Mesa OpenGL)
        uses: ssciwr/setup-mesa-dist-win@v1

      # NUEVO PASO: Instala un dispositivo de audio virtual mediante Chocolatey
      - name: Configurar Audio Virtual (Virtual Audio Cable)
        shell: powershell
        run: |
          choco install virtual-audio-cable --no-progress -y

      # Paso corregido inyectando el entorno completo
      - name: Build Mastering
        shell: cmd
        working-directory: Oxygen/sonic3air/___internal/mastering
        run: |
          set msbuildPath=msbuild
          
          echo === Compilando binarios iniciales ===
          msbuild ../../build/_vstudio/sonic3air.sln /property:Configuration=Release /property:Platform=x64 -verbosity:minimal
          
          echo === Inyectando controladores gráficos virtuales ===
          copy "C:\Windows\System32\opengl32.dll" "..\..\bin\Release_x64\" /y
          
          echo === Procesando scripts .lemon y empaquetando ===
          call mastering_windows_64bit.bat

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonic3air_windows_build
          path: Oxygen/sonic3air/___internal/_MASTER/
    
